# Records the environment and hashes of the exact files generated by a probe.
param(
    [Parameter(Mandatory=$true)][string]$OutputPath,
    [Parameter(Mandatory=$true)][string]$Groups,
    [string[]]$Files = @()
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$graphics = [System.Drawing.Graphics]::FromHwnd([IntPtr]::Zero)
try { $dpi = @($graphics.DpiX, $graphics.DpiY) } finally { $graphics.Dispose() }
$fonts = @()
foreach ($directory in @("$env:WINDIR\Fonts", "$env:LOCALAPPDATA\Microsoft\Windows\Fonts")) {
    if (!(Test-Path -LiteralPath $directory)) { continue }
    $fonts += @(Get-ChildItem -LiteralPath $directory -File | Where-Object {
        $_.Extension -in @('.ttf', '.ttc', '.otf')
    } | Sort-Object Name | ForEach-Object {
        [ordered]@{ name = $_.Name; location = $(if ($directory -eq "$env:WINDIR\Fonts") { 'system' } else { 'user' }); sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant() }
    })
}
$libraries = @('gdi32.dll', 'gdiplus.dll', 'win32u.dll') | ForEach-Object {
    $library = Get-Item -LiteralPath "$env:WINDIR\System32\$_" -ErrorAction SilentlyContinue
    if ($library) { [ordered]@{ name = $_; version = $library.VersionInfo.FileVersion; sha256 = (Get-FileHash -LiteralPath $library.FullName -Algorithm SHA256).Hash.ToLowerInvariant() } }
}
$references = @($Files | Sort-Object | ForEach-Object {
    $file = Get-Item -LiteralPath $_
    [ordered]@{ name = $file.Name; sha256 = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant() }
})
$manifest = [ordered]@{
    schemaVersion = 1
    capturedAt = [DateTime]::UtcNow.ToString('o')
    groups = $Groups
    os = [Environment]::OSVersion.VersionString
    build = (Get-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').UBR
    architecture = $env:PROCESSOR_ARCHITECTURE
    runnerImage = $env:ImageOS
    runnerImageVersion = $env:ImageVersion
    screenDpi = $dpi
    libraries = @($libraries)
    fonts = $fonts
    references = $references
}
# UTF-8 without a BOM can be read directly by JSON.parse on every platform.
[IO.File]::WriteAllText($OutputPath, ($manifest | ConvertTo-Json -Depth 6), (New-Object Text.UTF8Encoding($false)))
