# Generate the encodings missing from WHATWG TextDecoder using Windows NLS.
# Run with Windows PowerShell (.NET Framework): powershell.exe -File ...
$ErrorActionPreference = 'Stop'
$out = Join-Path $PSScriptRoot '../../src/emf-ansi-tables.ts'
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/gdi-fixtures/generate-ansi.ps1 from Windows code pages.')
$lines.Add('// U+FFFD marks an undefined Johab byte pair. No runtime encoding dependency.')
$oem = [Text.Encoding]::GetEncoding(437).GetString([byte[]](128..255))
$lines.Add('export const OEM437_HIGH = ' + (ConvertTo-Json -InputObject $oem -Compress) + ';')
$e = [Text.Encoding]::GetEncoding(1361, [Text.EncoderExceptionFallback]::new(), [Text.DecoderExceptionFallback]::new())
$lines.Add('export const JOHAB_ROWS: Record<number, string> = {')
for ($lead = 128; $lead -lt 256; $lead++) {
    $row = [Text.StringBuilder]::new()
    $valid = $false
    for ($trail = 0; $trail -lt 256; $trail++) {
        try {
            $s = $e.GetString([byte[]]($lead, $trail))
            if ($s.Length -ne 1) { $s = [string][char]0xfffd } else { $valid = $true }
        } catch { $s = [string][char]0xfffd }
        [void]$row.Append($s)
    }
    if ($valid) { $lines.Add("`t${lead}: " + (ConvertTo-Json -InputObject $row.ToString() -Compress) + ',') }
}
$lines.Add('};')
[IO.File]::WriteAllLines($out, $lines, [Text.UTF8Encoding]::new($false))
