/**
 * Rebuilds `src/emf-gdi-chroma-tie-data.ts` and `src/__fixtures__/gdi/halftone-chroma-ties.json.gz` (with its
 * environment manifest): the entries of Windows' 32^3 halftone colour cubes for chosen colorfulness / tint settings
 * where the native result differs from `colorAdjustmentMapper`'s u'v' formula.
 *
 * The formula lands on exact halves for the hue-preserving gamut normalisation (colorfulness alone: 255 * (c - lo) /
 * (hi - lo) of the palette colour, 1,658 exact halves in the four colorfulness cubes) and within about 5e-4 of a half
 * for the rest, and Windows breaks those ties by float noise of its own (about half go each way, whatever the double
 * sign of the error, the index ratio or the order of float32 operations). The chroma output is therefore exact except
 * for a fixed set of (colour, channel) entries per setting, one level off; this stores them, as flips of the formula's
 * rounded value, for the settings the committed captures use (and a few more measured the same way).
 *
 *   bun scripts/gdi-fixtures/generate-chroma-ties.ts
 *
 * Needs Windows PowerShell 5.1 (it calls `generate.ps1 chroma-cubes -TablesDir <temporary directory>`).
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';

import { colorAdjustmentMapper, DEFAULT_COLOR_ADJUSTMENT } from '../../src/emf-gdi-color-adjust';

const here = resolve(import.meta.dir, '.');
const root = resolve(here, '../..');
const settings: [number, number][] = [[40, 0], [40, 20], [50, 20], [-40, 0], [100, 0], [-100, 0], [20, 0], [70, 0], [0, 30], [0, -50], [0, 60]];
const PALETTE = Array.from({ length: 32 }, (_, n) => Math.round((n * 255) / 31));

const work = mkdtempSync(join(tmpdir(), 'chroma-cubes-'));
execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(here, 'generate.ps1'), 'chroma-cubes', '-TablesDir', work], { stdio: 'inherit' });

const captured: { colorfulness: number; redGreenTint: number; sha256: string; misses: number; flips: number[] }[] = [];
for (const [colorfulness, redGreenTint] of settings) {
	const cube = readFileSync(join(work, `chroma-cube-${colorfulness}-${redGreenTint}.bin`));
	const map = colorAdjustmentMapper({ ...DEFAULT_COLOR_ADJUSTMENT, colorfulness, redGreenTint }, { chromaTies: false });
	const flips: number[] = [];
	for (let i = 0; i < 32768; i++) {
		const v = map((PALETTE[i >> 10] << 16) | (PALETTE[(i >> 5) & 31] << 8) | PALETTE[i & 31]);
		const formula = [(v >> 16) & 255, (v >> 8) & 255, v & 255];
		for (let c = 0; c < 3; c++) {
			const native = cube[i * 3 + c];
			if (native === formula[c]) continue;
			if (Math.abs(native - formula[c]) !== 1) throw new Error(`entry ${i}/${c} of ${colorfulness},${redGreenTint} is more than one level off`);
			flips.push((i * 3 + c) * 2 + (native > formula[c] ? 1 : 0));
		}
	}
	captured.push({ colorfulness, redGreenTint, sha256: createHash('sha256').update(cube).digest('hex'), misses: flips.length, flips });
	console.log(`colorfulness ${colorfulness} tint ${redGreenTint}: ${flips.length} of 98304 channel values differ`);
}

const lines = captured.map(c => `\t'${c.colorfulness},${c.redGreenTint}': [${c.flips.join(',')}],`);
const module = `/**
 * Entries of Windows' halftone colour cubes where the native colorfulness / tint result differs by one level from the
 * u'v' formula of \`colorAdjustmentMapper\`: for each setting \`'colorfulness,tint'\` (no illuminant), the list of
 * \`(cubeIndex * 3 + channel) * 2 + up\`, where \`cubeIndex = (r * 32 + g) * 32 + b\` over the palette levels, \`channel\`
 * is 0 for red, and \`up\` is 1 when the native level is one above the formula's rounded value and 0 when it is one below.
 * Generated by \`scripts/gdi-fixtures/generate-chroma-ties.ts\` from \`src/__fixtures__/gdi/halftone-chroma-ties.json.gz\`
 * (native captures of 11 cubes: Windows breaks the formula's exact-half and near-half ties by float noise of its own).
 */
export const CHROMA_TIE_FLIPS: Readonly<Record<string, readonly number[]>> = {
${lines.join('\n')}
};
`;
writeFileSync(join(root, 'src/emf-gdi-chroma-tie-data.ts'), module);
const file = join(root, 'src/__fixtures__/gdi/halftone-chroma-ties.json.gz');
writeFileSync(file, gzipSync(Buffer.from(JSON.stringify({ version: 1, settings: captured })), { level: 9 }));
execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(here, 'capture-environment.ps1'), '-OutputPath', join(root, 'src/__fixtures__/gdi/environment-halftone-chroma-ties.json'), '-Groups', 'chroma-cubes', '-Files', file], { stdio: 'inherit' });
console.log('wrote', file);
