/** Pack the complete native colour-curve lookups and levels regression sweep.
 * Windows regeneration:
 *   powershell.exe -NoProfile -File scripts/gdi-fixtures/generate.ps1 image-effect-tables <temporary-directory>
 *   bun scripts/gdi-fixtures/generate-image-curves.ts <temporary-directory>
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateSync } from 'node:zlib';
import { createHash } from 'node:crypto';

const input = process.argv[2];
if (!input) throw new Error('Pass the directory generated by image-effect-tables');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
let source = `/** Native GDI+ colour-curve lookups for every valid integer adjustment.
 * Generated by scripts/gdi-fixtures/generate-image-curves.ts.
 * Inflate only the selected curve when it is first used. */
import { inflateZlibSync } from './png-decoder';

const packed = [
`;
const hashes: string[] = [];
for (let curve = 0; curve < 8; curve++) {
	const bytes = readFileSync(resolve(input, `curve-${curve}.bin`));
	source += `\t'${deflateSync(bytes, { level: 9 }).toString('base64')}',\n`;
	hashes.push(createHash('sha256').update(bytes).digest('hex'));
}
source += `];
const cache = new Map<number, Uint8Array>();

export function nativeCurveLookup(curve: number, intensity: number): Uint8Array {
	let data = cache.get(curve);
	if (!data) {
		const bytes = Uint8Array.from(atob(packed[curve]), (v) => v.charCodeAt(0));
		data = inflateZlibSync(bytes);
		cache.set(curve, data);
	}
	const min = curve < 2 ? -255 : curve < 6 ? -100 : curve === 6 ? 1 : 0;
	const offset = (intensity - min) * 256;
	return data.subarray(offset, offset + 256);
}
`;
writeFileSync(resolve(root, 'src/emf-plus-image-curves.ts'), source);
writeFileSync(resolve(root, 'src/__fixtures__/gdi/effect-curve-hashes.json'), JSON.stringify(hashes));
const settings = readFileSync(resolve(input, 'levels-settings.csv'), 'utf8').trim().split(/\r?\n/).map((line) => line.split(',').map(Number));
const expected = deflateSync(readFileSync(resolve(input, 'levels-sweep.bin')), { level: 9 }).toString('base64');
writeFileSync(resolve(root, 'src/__fixtures__/gdi/effect-levels-sweep.json'), JSON.stringify({ settings, expected }));
