/**
 * Rebuilds `src/__fixtures__/gdi/halftone-mixed-engine.json.gz` (and its environment manifest): native HALFTONE
 * stretches behind `halftoneMixedEngine` and the despeckle size bands in `src/emf-gdi-stretch.ts`. The sources are
 * generated by `src/halftone-mixed-engine.fixture-helper.ts`; `HalftoneBoundaryProbe.cs` stretches each one (version 2
 * input) and returns the destination. The capture keeps the SHA-256 of every native output plus the bytes of the
 * cases the current engine does not reproduce exactly (the test pins their residuals).
 *
 *   bun scripts/gdi-fixtures/generate-halftone-mixed-engine.ts
 *
 * Needs Windows PowerShell 5.1 (it calls `generate.ps1 halftone-boundary -TablesDir <temporary directory>`).
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';

import { stretchHalftone } from '../../src/emf-gdi-stretch';
import { mixedEngineCases, mixedSource } from '../../src/halftone-mixed-engine.fixture-helper';

const here = resolve(import.meta.dir, '.');
const output = resolve(here, '../../src/__fixtures__/gdi');
const work = mkdtempSync(join(tmpdir(), 'halftone-mixed-engine-'));

const cases = mixedEngineCases();
const sources = cases.map(c => mixedSource(c.kind, c.w, c.h, c.seed));

function inputFile(indices: number[]): Buffer {
	const parts: Buffer[] = [];
	const head = Buffer.alloc(8); head.writeInt32LE(-indices.length, 0); head.writeInt32LE(1, 4); parts.push(head);
	for (const i of indices) {
		const c = cases[i];
		const h = Buffer.alloc(36);
		[c.w, c.h, 0, 0, c.w, c.h, c.dw, c.dh, 0].forEach((v, k) => h.writeInt32LE(v, k * 4));
		const bgra = new Uint8Array(c.w * c.h * 4);
		for (let p = 0; p < c.w * c.h; p++) bgra.set([sources[i][p * 3 + 2], sources[i][p * 3 + 1], sources[i][p * 3], 255], p * 4);
		parts.push(h, Buffer.from(bgra));
	}
	return Buffer.concat(parts);
}

const BATCH = 6;
const batches: { name: string; indices: number[] }[] = [];
for (let first = 0; first < cases.length; first += BATCH) {
	const indices = cases.slice(first, first + BATCH).map((_, k) => first + k);
	const name = `case-${String(first).padStart(5, '0')}`;
	writeFileSync(join(work, name + '.hbin'), inputFile(indices));
	batches.push({ name, indices });
}
execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(here, 'generate.ps1'), 'halftone-boundary', '-TablesDir', work], { stdio: 'inherit' });

const natives: Uint8Array[] = new Array(cases.length);
for (const { name, indices } of batches) {
	const data = readFileSync(join(work, name + '.hout'));
	let p = 0;
	if (data.readInt32LE(p) !== indices.length) throw new Error(name + ': result count');
	p += 4;
	for (const i of indices) {
		const c = cases[i];
		const sw = data.readInt32LE(p), sh = data.readInt32LE(p + 4); p += 16 + 4 * (sw + sh);
		const rgb = new Uint8Array(c.dw * c.dh * 3);
		for (let k = 0; k < c.dw * c.dh; k++) { rgb[k * 3] = data[p + k * 4 + 2]; rgb[k * 3 + 1] = data[p + k * 4 + 1]; rgb[k * 3 + 2] = data[p + k * 4]; }
		p += c.dw * c.dh * 4;
		natives[i] = rgb;
	}
}

let exact = 0;
const captured = {
	version: 1,
	cases: cases.map((c, i) => {
		const data = new Uint8ClampedArray(c.w * c.h * 4);
		for (let p = 0; p < c.w * c.h; p++) data.set([sources[i][p * 3], sources[i][p * 3 + 1], sources[i][p * 3 + 2], 255], p * 4);
		const ours = stretchHalftone({ width: c.w, height: c.h, data }, 0, 0, c.w, c.h, c.dw, c.dh).data;
		let bad = 0;
		for (let k = 0; k < c.dw * c.dh; k++) for (let ch = 0; ch < 3; ch++) if (ours[k * 4 + ch] !== natives[i][k * 3 + ch]) bad++;
		if (bad === 0) exact++;
		const hash = createHash('sha256').update(natives[i]).digest('hex');
		return bad === 0 ? { id: c.id, hash } : { id: c.id, hash, output: Buffer.from(natives[i]).toString('base64') };
	}),
};
const file = join(output, 'halftone-mixed-engine.json.gz');
writeFileSync(file, gzipSync(Buffer.from(JSON.stringify(captured)), { level: 9 }));
execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(here, 'capture-environment.ps1'), '-OutputPath', join(output, 'environment-halftone-mixed-engine.json'), '-Groups', 'halftone-mixed-engine', '-Files', file], { stdio: 'inherit' });
console.log('wrote', file, `${cases.length} cases, ${exact} exact with the current engine`);
