/**
 * Rebuilds `src/__fixtures__/gdi/halftone-filtered.json.gz` (and its environment manifest): native HALFTONE
 * enlargements that take the filtered branch, behind `halftoneFilterEnlarge` in `src/emf-gdi-stretch.ts`.
 * The sources are generated by `src/halftone-filtered.fixture-helper.ts`; `HalftoneBoundaryProbe.cs` stretches
 * each one (version 2 input, flags select mirroring and colour adjustment) and returns the destination.
 *
 *   bun scripts/gdi-fixtures/generate-halftone-filtered.ts
 *
 * Needs Windows PowerShell 5.1 (it calls `generate.ps1 halftone-boundary -TablesDir <temporary directory>`).
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';

import {
	PROFILE_LENGTH, PROFILE_OTHER, PROFILE_SCALES, PROFILE_SEEDS, filteredCases, filteredSource, profileSource,
} from '../../src/halftone-filtered.fixture-helper';

const here = resolve(import.meta.dir, '.');
const output = resolve(here, '../../src/__fixtures__/gdi');
const work = mkdtempSync(join(tmpdir(), 'halftone-filtered-'));

interface Job { bw: number; bh: number; dw: number; dh: number; flags: number; rgb: Uint8Array }

function bgra(rgb: Uint8Array): Uint8Array {
	const out = new Uint8Array((rgb.length / 3) * 4);
	for (let i = 0, o = 0; i < rgb.length; i += 3, o += 4) {
		out[o] = rgb[i + 2]; out[o + 1] = rgb[i + 1]; out[o + 2] = rgb[i]; out[o + 3] = 255;
	}
	return out;
}

function inputFile(jobs: Job[]): Buffer {
	const parts: Buffer[] = [];
	const head = Buffer.alloc(8); head.writeInt32LE(-jobs.length, 0); head.writeInt32LE(1, 4); parts.push(head);
	for (const job of jobs) {
		const h = Buffer.alloc(36);
		[job.bw, job.bh, 0, 0, job.bw, job.bh, job.dw, job.dh, job.flags].forEach((v, i) => h.writeInt32LE(v, i * 4));
		parts.push(h, Buffer.from(bgra(job.rgb)));
	}
	return Buffer.concat(parts);
}

/** Destination RGB bytes of every job of `<name>.hout`. */
function readOutput(name: string, jobs: Job[]): Uint8Array[] {
	const data = readFileSync(join(work, name + '.hout'));
	let p = 0;
	const count = data.readInt32LE(p); p += 4;
	if (count !== jobs.length) throw new Error(`${name}: ${count} results for ${jobs.length} jobs`);
	return jobs.map(job => {
		const sw = data.readInt32LE(p), sh = data.readInt32LE(p + 4); p += 16 + 4 * (sw + sh);
		const length = job.dw * job.dh * 4;
		const bytes = data.subarray(p, p + length); p += length;
		const rgb = new Uint8Array(job.dw * job.dh * 3);
		for (let i = 0; i < job.dw * job.dh; i++) { rgb[i * 3] = bytes[i * 4 + 2]; rgb[i * 3 + 1] = bytes[i * 4 + 1]; rgb[i * 3 + 2] = bytes[i * 4]; }
		return rgb;
	});
}

const cases = filteredCases();
const caseJobs: Job[] = cases.map(c => ({ bw: c.w, bh: c.h, dw: c.dw, dh: c.dh, flags: c.flags, rgb: filteredSource(c.kind, c.w, c.h) }));
const profiles: { axis: 'v' | 'h'; seed: number; scale: number }[] = [];
const profileJobs: Job[] = [];
for (const axis of ['v', 'h'] as const) for (let seed = 0; seed < PROFILE_SEEDS; seed++) for (const scale of PROFILE_SCALES) {
	const s = profileSource(axis, seed);
	profiles.push({ axis, seed, scale });
	profileJobs.push({ bw: s.w, bh: s.h, dw: s.w * scale, dh: s.h * scale, flags: 0, rgb: s.rgb });
}

// One file per case keeps every batch small; the probe runs all <name>.hbin files of the directory.
const BATCH = 8;
const names: { name: string; jobs: Job[] }[] = [];
const batches = (prefix: string, jobs: Job[]): void => {
	for (let first = 0; first < jobs.length; first += BATCH) {
		const slice = jobs.slice(first, first + BATCH);
		const name = `${prefix}-${String(first).padStart(4, '0')}`;
		writeFileSync(join(work, name + '.hbin'), inputFile(slice));
		names.push({ name, jobs: slice });
	}
};
batches('case', caseJobs);
batches('profile', profileJobs);
execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(here, 'generate.ps1'), 'halftone-boundary', '-TablesDir', work], { stdio: 'inherit' });

const outputs = new Map<string, Uint8Array[]>();
for (const { name, jobs } of names) outputs.set(name, readOutput(name, jobs));
const collect = (prefix: string): Uint8Array[] => names.filter(n => n.name.startsWith(prefix + '-')).flatMap(n => outputs.get(n.name)!);
const caseOutputs = collect('case');
const profileOutputs = collect('profile');

const captured = {
	version: 1,
	cases: cases.map((c, i) => ({ id: c.id, output: Buffer.from(caseOutputs[i]).toString('base64') })),
	profiles: profiles.map((p, i) => {
		// One line of the destination: a column (vertical profile) or a row (horizontal profile) away from the edges.
		const dw = PROFILE_OTHER * p.scale;
		const line = new Uint8Array(PROFILE_LENGTH * p.scale * 3);
		const out = profileOutputs[i];
		for (let t = 0; t < PROFILE_LENGTH * p.scale; t++) {
			const from = p.axis === 'v' ? (t * dw + 3) * 3 : (3 * PROFILE_LENGTH * p.scale + t) * 3;
			line.set(out.subarray(from, from + 3), t * 3);
		}
		return { ...p, line: Buffer.from(line).toString('base64') };
	}),
};
const file = join(output, 'halftone-filtered.json.gz');
writeFileSync(file, gzipSync(Buffer.from(JSON.stringify(captured)), { level: 9 }));
execFileSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(here, 'capture-environment.ps1'), '-OutputPath', join(output, 'environment-halftone-filtered.json'), '-Groups', 'halftone-filtered', '-Files', file], { stdio: 'inherit' });
console.log('wrote', file, `${cases.length} cases, ${profiles.length} profiles`);
